(cl:in-package segway_msgs-srv)
(cl:export '(CFG_IN_SITU_ROTATION_FUNCTION-VAL
          CFG_IN_SITU_ROTATION_FUNCTION
          CFG_IN_SITU_ROTATION_RESULT-VAL
          CFG_IN_SITU_ROTATION_RESULT
))