(cl:in-package segway_msgs-srv)
(cl:export '(ROS_SET_FORWARD_MAX_VEL-VAL
          ROS_SET_FORWARD_MAX_VEL
          ROS_SET_BACKWARD_MAX_VEL-VAL
          ROS_SET_BACKWARD_MAX_VEL
          ROS_SET_ANGULAR_MAX_VEL-VAL
          ROS_SET_ANGULAR_MAX_VEL
          CHASSIS_SET_MAX_VEL_RESULT-VAL
          CHASSIS_SET_MAX_VEL_RESULT
))