// Generated by gencpp from file segway_msgs/ros_get_chassis_SN_cmdResponse.msg
// DO NOT EDIT!


#ifndef SEGWAY_MSGS_MESSAGE_ROS_GET_CHASSIS_SN_CMDRESPONSE_H
#define SEGWAY_MSGS_MESSAGE_ROS_GET_CHASSIS_SN_CMDRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace segway_msgs
{
template <class ContainerAllocator>
struct ros_get_chassis_SN_cmdResponse_
{
  typedef ros_get_chassis_SN_cmdResponse_<ContainerAllocator> Type;

  ros_get_chassis_SN_cmdResponse_()
    : chassis_SN()  {
    }
  ros_get_chassis_SN_cmdResponse_(const ContainerAllocator& _alloc)
    : chassis_SN(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _chassis_SN_type;
  _chassis_SN_type chassis_SN;





  typedef boost::shared_ptr< ::segway_msgs::ros_get_chassis_SN_cmdResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::segway_msgs::ros_get_chassis_SN_cmdResponse_<ContainerAllocator> const> ConstPtr;

}; // struct ros_get_chassis_SN_cmdResponse_

typedef ::segway_msgs::ros_get_chassis_SN_cmdResponse_<std::allocator<void> > ros_get_chassis_SN_cmdResponse;

typedef boost::shared_ptr< ::segway_msgs::ros_get_chassis_SN_cmdResponse > ros_get_chassis_SN_cmdResponsePtr;
typedef boost::shared_ptr< ::segway_msgs::ros_get_chassis_SN_cmdResponse const> ros_get_chassis_SN_cmdResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::segway_msgs::ros_get_chassis_SN_cmdResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::segway_msgs::ros_get_chassis_SN_cmdResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::segway_msgs::ros_get_chassis_SN_cmdResponse_<ContainerAllocator1> & lhs, const ::segway_msgs::ros_get_chassis_SN_cmdResponse_<ContainerAllocator2> & rhs)
{
  return lhs.chassis_SN == rhs.chassis_SN;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::segway_msgs::ros_get_chassis_SN_cmdResponse_<ContainerAllocator1> & lhs, const ::segway_msgs::ros_get_chassis_SN_cmdResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace segway_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::segway_msgs::ros_get_chassis_SN_cmdResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::segway_msgs::ros_get_chassis_SN_cmdResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::segway_msgs::ros_get_chassis_SN_cmdResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::segway_msgs::ros_get_chassis_SN_cmdResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::segway_msgs::ros_get_chassis_SN_cmdResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::segway_msgs::ros_get_chassis_SN_cmdResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::segway_msgs::ros_get_chassis_SN_cmdResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9ca061794271842fe318962203ef8f2d";
  }

  static const char* value(const ::segway_msgs::ros_get_chassis_SN_cmdResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9ca061794271842fULL;
  static const uint64_t static_value2 = 0xe318962203ef8f2dULL;
};

template<class ContainerAllocator>
struct DataType< ::segway_msgs::ros_get_chassis_SN_cmdResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "segway_msgs/ros_get_chassis_SN_cmdResponse";
  }

  static const char* value(const ::segway_msgs::ros_get_chassis_SN_cmdResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::segway_msgs::ros_get_chassis_SN_cmdResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string  chassis_SN \n"
;
  }

  static const char* value(const ::segway_msgs::ros_get_chassis_SN_cmdResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::segway_msgs::ros_get_chassis_SN_cmdResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.chassis_SN);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ros_get_chassis_SN_cmdResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::segway_msgs::ros_get_chassis_SN_cmdResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::segway_msgs::ros_get_chassis_SN_cmdResponse_<ContainerAllocator>& v)
  {
    s << indent << "chassis_SN: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.chassis_SN);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SEGWAY_MSGS_MESSAGE_ROS_GET_CHASSIS_SN_CMDRESPONSE_H
