// Generated by gencpp from file segway_msgs/ros_stop_chassis_rotate_cmdRequest.msg
// DO NOT EDIT!


#ifndef SEGWAY_MSGS_MESSAGE_ROS_STOP_CHASSIS_ROTATE_CMDREQUEST_H
#define SEGWAY_MSGS_MESSAGE_ROS_STOP_CHASSIS_ROTATE_CMDREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace segway_msgs
{
template <class ContainerAllocator>
struct ros_stop_chassis_rotate_cmdRequest_
{
  typedef ros_stop_chassis_rotate_cmdRequest_<ContainerAllocator> Type;

  ros_stop_chassis_rotate_cmdRequest_()
    : ros_stop_chassis_rotate_cmd(false)  {
    }
  ros_stop_chassis_rotate_cmdRequest_(const ContainerAllocator& _alloc)
    : ros_stop_chassis_rotate_cmd(false)  {
  (void)_alloc;
    }



   typedef uint8_t _ros_stop_chassis_rotate_cmd_type;
  _ros_stop_chassis_rotate_cmd_type ros_stop_chassis_rotate_cmd;





  typedef boost::shared_ptr< ::segway_msgs::ros_stop_chassis_rotate_cmdRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::segway_msgs::ros_stop_chassis_rotate_cmdRequest_<ContainerAllocator> const> ConstPtr;

}; // struct ros_stop_chassis_rotate_cmdRequest_

typedef ::segway_msgs::ros_stop_chassis_rotate_cmdRequest_<std::allocator<void> > ros_stop_chassis_rotate_cmdRequest;

typedef boost::shared_ptr< ::segway_msgs::ros_stop_chassis_rotate_cmdRequest > ros_stop_chassis_rotate_cmdRequestPtr;
typedef boost::shared_ptr< ::segway_msgs::ros_stop_chassis_rotate_cmdRequest const> ros_stop_chassis_rotate_cmdRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::segway_msgs::ros_stop_chassis_rotate_cmdRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::segway_msgs::ros_stop_chassis_rotate_cmdRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::segway_msgs::ros_stop_chassis_rotate_cmdRequest_<ContainerAllocator1> & lhs, const ::segway_msgs::ros_stop_chassis_rotate_cmdRequest_<ContainerAllocator2> & rhs)
{
  return lhs.ros_stop_chassis_rotate_cmd == rhs.ros_stop_chassis_rotate_cmd;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::segway_msgs::ros_stop_chassis_rotate_cmdRequest_<ContainerAllocator1> & lhs, const ::segway_msgs::ros_stop_chassis_rotate_cmdRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace segway_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::segway_msgs::ros_stop_chassis_rotate_cmdRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::segway_msgs::ros_stop_chassis_rotate_cmdRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::segway_msgs::ros_stop_chassis_rotate_cmdRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::segway_msgs::ros_stop_chassis_rotate_cmdRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::segway_msgs::ros_stop_chassis_rotate_cmdRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::segway_msgs::ros_stop_chassis_rotate_cmdRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::segway_msgs::ros_stop_chassis_rotate_cmdRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9f6beddff2ced178c7184a3e5e246129";
  }

  static const char* value(const ::segway_msgs::ros_stop_chassis_rotate_cmdRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9f6beddff2ced178ULL;
  static const uint64_t static_value2 = 0xc7184a3e5e246129ULL;
};

template<class ContainerAllocator>
struct DataType< ::segway_msgs::ros_stop_chassis_rotate_cmdRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "segway_msgs/ros_stop_chassis_rotate_cmdRequest";
  }

  static const char* value(const ::segway_msgs::ros_stop_chassis_rotate_cmdRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::segway_msgs::ros_stop_chassis_rotate_cmdRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool   ros_stop_chassis_rotate_cmd\n"
;
  }

  static const char* value(const ::segway_msgs::ros_stop_chassis_rotate_cmdRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::segway_msgs::ros_stop_chassis_rotate_cmdRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.ros_stop_chassis_rotate_cmd);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ros_stop_chassis_rotate_cmdRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::segway_msgs::ros_stop_chassis_rotate_cmdRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::segway_msgs::ros_stop_chassis_rotate_cmdRequest_<ContainerAllocator>& v)
  {
    s << indent << "ros_stop_chassis_rotate_cmd: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.ros_stop_chassis_rotate_cmd);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SEGWAY_MSGS_MESSAGE_ROS_STOP_CHASSIS_ROTATE_CMDREQUEST_H
