// Generated by gencpp from file segway_msgs/ros_get_rotate_function_cfg_cmd.msg
// DO NOT EDIT!


#ifndef SEGWAY_MSGS_MESSAGE_ROS_GET_ROTATE_FUNCTION_CFG_CMD_H
#define SEGWAY_MSGS_MESSAGE_ROS_GET_ROTATE_FUNCTION_CFG_CMD_H

#include <ros/service_traits.h>


#include <segway_msgs/ros_get_rotate_function_cfg_cmdRequest.h>
#include <segway_msgs/ros_get_rotate_function_cfg_cmdResponse.h>


namespace segway_msgs
{

struct ros_get_rotate_function_cfg_cmd
{

typedef ros_get_rotate_function_cfg_cmdRequest Request;
typedef ros_get_rotate_function_cfg_cmdResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ros_get_rotate_function_cfg_cmd
} // namespace segway_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::segway_msgs::ros_get_rotate_function_cfg_cmd > {
  static const char* value()
  {
    return "b904daa6a5eac6934cf3984ac629f440";
  }

  static const char* value(const ::segway_msgs::ros_get_rotate_function_cfg_cmd&) { return value(); }
};

template<>
struct DataType< ::segway_msgs::ros_get_rotate_function_cfg_cmd > {
  static const char* value()
  {
    return "segway_msgs/ros_get_rotate_function_cfg_cmd";
  }

  static const char* value(const ::segway_msgs::ros_get_rotate_function_cfg_cmd&) { return value(); }
};


// service_traits::MD5Sum< ::segway_msgs::ros_get_rotate_function_cfg_cmdRequest> should match
// service_traits::MD5Sum< ::segway_msgs::ros_get_rotate_function_cfg_cmd >
template<>
struct MD5Sum< ::segway_msgs::ros_get_rotate_function_cfg_cmdRequest>
{
  static const char* value()
  {
    return MD5Sum< ::segway_msgs::ros_get_rotate_function_cfg_cmd >::value();
  }
  static const char* value(const ::segway_msgs::ros_get_rotate_function_cfg_cmdRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::segway_msgs::ros_get_rotate_function_cfg_cmdRequest> should match
// service_traits::DataType< ::segway_msgs::ros_get_rotate_function_cfg_cmd >
template<>
struct DataType< ::segway_msgs::ros_get_rotate_function_cfg_cmdRequest>
{
  static const char* value()
  {
    return DataType< ::segway_msgs::ros_get_rotate_function_cfg_cmd >::value();
  }
  static const char* value(const ::segway_msgs::ros_get_rotate_function_cfg_cmdRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::segway_msgs::ros_get_rotate_function_cfg_cmdResponse> should match
// service_traits::MD5Sum< ::segway_msgs::ros_get_rotate_function_cfg_cmd >
template<>
struct MD5Sum< ::segway_msgs::ros_get_rotate_function_cfg_cmdResponse>
{
  static const char* value()
  {
    return MD5Sum< ::segway_msgs::ros_get_rotate_function_cfg_cmd >::value();
  }
  static const char* value(const ::segway_msgs::ros_get_rotate_function_cfg_cmdResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::segway_msgs::ros_get_rotate_function_cfg_cmdResponse> should match
// service_traits::DataType< ::segway_msgs::ros_get_rotate_function_cfg_cmd >
template<>
struct DataType< ::segway_msgs::ros_get_rotate_function_cfg_cmdResponse>
{
  static const char* value()
  {
    return DataType< ::segway_msgs::ros_get_rotate_function_cfg_cmd >::value();
  }
  static const char* value(const ::segway_msgs::ros_get_rotate_function_cfg_cmdResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SEGWAY_MSGS_MESSAGE_ROS_GET_ROTATE_FUNCTION_CFG_CMD_H
