// Generated by gencpp from file segway_msgs/ros_set_cfg_rotate_function_cmdResponse.msg
// DO NOT EDIT!


#ifndef SEGWAY_MSGS_MESSAGE_ROS_SET_CFG_ROTATE_FUNCTION_CMDRESPONSE_H
#define SEGWAY_MSGS_MESSAGE_ROS_SET_CFG_ROTATE_FUNCTION_CMDRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace segway_msgs
{
template <class ContainerAllocator>
struct ros_set_cfg_rotate_function_cmdResponse_
{
  typedef ros_set_cfg_rotate_function_cmdResponse_<ContainerAllocator> Type;

  ros_set_cfg_rotate_function_cmdResponse_()
    : cfg_in_situ_rotation_result(0)  {
    }
  ros_set_cfg_rotate_function_cmdResponse_(const ContainerAllocator& _alloc)
    : cfg_in_situ_rotation_result(0)  {
  (void)_alloc;
    }



   typedef uint8_t _cfg_in_situ_rotation_result_type;
  _cfg_in_situ_rotation_result_type cfg_in_situ_rotation_result;





  typedef boost::shared_ptr< ::segway_msgs::ros_set_cfg_rotate_function_cmdResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::segway_msgs::ros_set_cfg_rotate_function_cmdResponse_<ContainerAllocator> const> ConstPtr;

}; // struct ros_set_cfg_rotate_function_cmdResponse_

typedef ::segway_msgs::ros_set_cfg_rotate_function_cmdResponse_<std::allocator<void> > ros_set_cfg_rotate_function_cmdResponse;

typedef boost::shared_ptr< ::segway_msgs::ros_set_cfg_rotate_function_cmdResponse > ros_set_cfg_rotate_function_cmdResponsePtr;
typedef boost::shared_ptr< ::segway_msgs::ros_set_cfg_rotate_function_cmdResponse const> ros_set_cfg_rotate_function_cmdResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::segway_msgs::ros_set_cfg_rotate_function_cmdResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::segway_msgs::ros_set_cfg_rotate_function_cmdResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::segway_msgs::ros_set_cfg_rotate_function_cmdResponse_<ContainerAllocator1> & lhs, const ::segway_msgs::ros_set_cfg_rotate_function_cmdResponse_<ContainerAllocator2> & rhs)
{
  return lhs.cfg_in_situ_rotation_result == rhs.cfg_in_situ_rotation_result;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::segway_msgs::ros_set_cfg_rotate_function_cmdResponse_<ContainerAllocator1> & lhs, const ::segway_msgs::ros_set_cfg_rotate_function_cmdResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace segway_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::segway_msgs::ros_set_cfg_rotate_function_cmdResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::segway_msgs::ros_set_cfg_rotate_function_cmdResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::segway_msgs::ros_set_cfg_rotate_function_cmdResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::segway_msgs::ros_set_cfg_rotate_function_cmdResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::segway_msgs::ros_set_cfg_rotate_function_cmdResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::segway_msgs::ros_set_cfg_rotate_function_cmdResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::segway_msgs::ros_set_cfg_rotate_function_cmdResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2e36c317f00e17337b836533734cab1e";
  }

  static const char* value(const ::segway_msgs::ros_set_cfg_rotate_function_cmdResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2e36c317f00e1733ULL;
  static const uint64_t static_value2 = 0x7b836533734cab1eULL;
};

template<class ContainerAllocator>
struct DataType< ::segway_msgs::ros_set_cfg_rotate_function_cmdResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "segway_msgs/ros_set_cfg_rotate_function_cmdResponse";
  }

  static const char* value(const ::segway_msgs::ros_set_cfg_rotate_function_cmdResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::segway_msgs::ros_set_cfg_rotate_function_cmdResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8   cfg_in_situ_rotation_result\n"
;
  }

  static const char* value(const ::segway_msgs::ros_set_cfg_rotate_function_cmdResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::segway_msgs::ros_set_cfg_rotate_function_cmdResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.cfg_in_situ_rotation_result);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ros_set_cfg_rotate_function_cmdResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::segway_msgs::ros_set_cfg_rotate_function_cmdResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::segway_msgs::ros_set_cfg_rotate_function_cmdResponse_<ContainerAllocator>& v)
  {
    s << indent << "cfg_in_situ_rotation_result: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.cfg_in_situ_rotation_result);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SEGWAY_MSGS_MESSAGE_ROS_SET_CFG_ROTATE_FUNCTION_CMDRESPONSE_H
