// Generated by gencpp from file segway_msgs/ros_enable_chassis_rotate_cmd.msg
// DO NOT EDIT!


#ifndef SEGWAY_MSGS_MESSAGE_ROS_ENABLE_CHASSIS_ROTATE_CMD_H
#define SEGWAY_MSGS_MESSAGE_ROS_ENABLE_CHASSIS_ROTATE_CMD_H

#include <ros/service_traits.h>


#include <segway_msgs/ros_enable_chassis_rotate_cmdRequest.h>
#include <segway_msgs/ros_enable_chassis_rotate_cmdResponse.h>


namespace segway_msgs
{

struct ros_enable_chassis_rotate_cmd
{

typedef ros_enable_chassis_rotate_cmdRequest Request;
typedef ros_enable_chassis_rotate_cmdResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ros_enable_chassis_rotate_cmd
} // namespace segway_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::segway_msgs::ros_enable_chassis_rotate_cmd > {
  static const char* value()
  {
    return "ae05e14660d3834a53587b4a303f4cb1";
  }

  static const char* value(const ::segway_msgs::ros_enable_chassis_rotate_cmd&) { return value(); }
};

template<>
struct DataType< ::segway_msgs::ros_enable_chassis_rotate_cmd > {
  static const char* value()
  {
    return "segway_msgs/ros_enable_chassis_rotate_cmd";
  }

  static const char* value(const ::segway_msgs::ros_enable_chassis_rotate_cmd&) { return value(); }
};


// service_traits::MD5Sum< ::segway_msgs::ros_enable_chassis_rotate_cmdRequest> should match
// service_traits::MD5Sum< ::segway_msgs::ros_enable_chassis_rotate_cmd >
template<>
struct MD5Sum< ::segway_msgs::ros_enable_chassis_rotate_cmdRequest>
{
  static const char* value()
  {
    return MD5Sum< ::segway_msgs::ros_enable_chassis_rotate_cmd >::value();
  }
  static const char* value(const ::segway_msgs::ros_enable_chassis_rotate_cmdRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::segway_msgs::ros_enable_chassis_rotate_cmdRequest> should match
// service_traits::DataType< ::segway_msgs::ros_enable_chassis_rotate_cmd >
template<>
struct DataType< ::segway_msgs::ros_enable_chassis_rotate_cmdRequest>
{
  static const char* value()
  {
    return DataType< ::segway_msgs::ros_enable_chassis_rotate_cmd >::value();
  }
  static const char* value(const ::segway_msgs::ros_enable_chassis_rotate_cmdRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::segway_msgs::ros_enable_chassis_rotate_cmdResponse> should match
// service_traits::MD5Sum< ::segway_msgs::ros_enable_chassis_rotate_cmd >
template<>
struct MD5Sum< ::segway_msgs::ros_enable_chassis_rotate_cmdResponse>
{
  static const char* value()
  {
    return MD5Sum< ::segway_msgs::ros_enable_chassis_rotate_cmd >::value();
  }
  static const char* value(const ::segway_msgs::ros_enable_chassis_rotate_cmdResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::segway_msgs::ros_enable_chassis_rotate_cmdResponse> should match
// service_traits::DataType< ::segway_msgs::ros_enable_chassis_rotate_cmd >
template<>
struct DataType< ::segway_msgs::ros_enable_chassis_rotate_cmdResponse>
{
  static const char* value()
  {
    return DataType< ::segway_msgs::ros_enable_chassis_rotate_cmd >::value();
  }
  static const char* value(const ::segway_msgs::ros_enable_chassis_rotate_cmdResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SEGWAY_MSGS_MESSAGE_ROS_ENABLE_CHASSIS_ROTATE_CMD_H
