# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from segway_msgs/bms_fb.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class bms_fb(genpy.Message):
  _md5sum = "558ba6f83cd88272c1434058df263b3b"
  _type = "segway_msgs/bms_fb"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """int16  bat_soc    
int16  bat_charging 
int32  bat_vol 
int32  bat_current 
int16  bat_temp
"""
  __slots__ = ['bat_soc','bat_charging','bat_vol','bat_current','bat_temp']
  _slot_types = ['int16','int16','int32','int32','int16']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       bat_soc,bat_charging,bat_vol,bat_current,bat_temp

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(bms_fb, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.bat_soc is None:
        self.bat_soc = 0
      if self.bat_charging is None:
        self.bat_charging = 0
      if self.bat_vol is None:
        self.bat_vol = 0
      if self.bat_current is None:
        self.bat_current = 0
      if self.bat_temp is None:
        self.bat_temp = 0
    else:
      self.bat_soc = 0
      self.bat_charging = 0
      self.bat_vol = 0
      self.bat_current = 0
      self.bat_temp = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_2h2ih().pack(_x.bat_soc, _x.bat_charging, _x.bat_vol, _x.bat_current, _x.bat_temp))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 14
      (_x.bat_soc, _x.bat_charging, _x.bat_vol, _x.bat_current, _x.bat_temp,) = _get_struct_2h2ih().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_2h2ih().pack(_x.bat_soc, _x.bat_charging, _x.bat_vol, _x.bat_current, _x.bat_temp))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 14
      (_x.bat_soc, _x.bat_charging, _x.bat_vol, _x.bat_current, _x.bat_temp,) = _get_struct_2h2ih().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_2h2ih = None
def _get_struct_2h2ih():
    global _struct_2h2ih
    if _struct_2h2ih is None:
        _struct_2h2ih = struct.Struct("<2h2ih")
    return _struct_2h2ih
