# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from segway_msgs/speed_fb.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class speed_fb(genpy.Message):
  _md5sum = "30be48766c9248b4c4c4b871092b7330"
  _type = "segway_msgs/speed_fb"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """float32 car_speed
float32 turn_speed
float32 fl_speed
float32 fr_speed
float32 rl_speed
float32 rr_speed
uint64 speed_timestamp"""
  __slots__ = ['car_speed','turn_speed','fl_speed','fr_speed','rl_speed','rr_speed','speed_timestamp']
  _slot_types = ['float32','float32','float32','float32','float32','float32','uint64']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       car_speed,turn_speed,fl_speed,fr_speed,rl_speed,rr_speed,speed_timestamp

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(speed_fb, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.car_speed is None:
        self.car_speed = 0.
      if self.turn_speed is None:
        self.turn_speed = 0.
      if self.fl_speed is None:
        self.fl_speed = 0.
      if self.fr_speed is None:
        self.fr_speed = 0.
      if self.rl_speed is None:
        self.rl_speed = 0.
      if self.rr_speed is None:
        self.rr_speed = 0.
      if self.speed_timestamp is None:
        self.speed_timestamp = 0
    else:
      self.car_speed = 0.
      self.turn_speed = 0.
      self.fl_speed = 0.
      self.fr_speed = 0.
      self.rl_speed = 0.
      self.rr_speed = 0.
      self.speed_timestamp = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_6fQ().pack(_x.car_speed, _x.turn_speed, _x.fl_speed, _x.fr_speed, _x.rl_speed, _x.rr_speed, _x.speed_timestamp))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 32
      (_x.car_speed, _x.turn_speed, _x.fl_speed, _x.fr_speed, _x.rl_speed, _x.rr_speed, _x.speed_timestamp,) = _get_struct_6fQ().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_6fQ().pack(_x.car_speed, _x.turn_speed, _x.fl_speed, _x.fr_speed, _x.rl_speed, _x.rr_speed, _x.speed_timestamp))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 32
      (_x.car_speed, _x.turn_speed, _x.fl_speed, _x.fr_speed, _x.rl_speed, _x.rr_speed, _x.speed_timestamp,) = _get_struct_6fQ().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_6fQ = None
def _get_struct_6fQ():
    global _struct_6fQ
    if _struct_6fQ is None:
        _struct_6fQ = struct.Struct("<6fQ")
    return _struct_6fQ
