(cl:in-package segway_msgs-msg)
(cl:export '(HOST_ERROR-VAL
          HOST_ERROR
          CENTRAL_ERROR-VAL
          CENTRAL_ERROR
          FRONT_LEFT_MOTOR_ERROR-VAL
          FRONT_LEFT_MOTOR_ERROR
          FRONT_RIGHT_MOTOR_ERROR-VAL
          FRONT_RIGHT_MOTOR_ERROR
          REAR_LEFT_MOTOR_ERROR-VAL
          REAR_LEFT_MOTOR_ERROR
          REAR_RIGHT_MOTOR_ERROR-VAL
          REAR_RIGHT_MOTOR_ERROR
          BMS_ERROR-VAL
          BMS_ERROR
          BRAKE_ERROR-VAL
          BRAKE_ERROR
))