; Auto-generated. Do not edit!


(cl:in-package segway_msgs-msg)


;//! \htmlinclude ros_set_iap_cmdResult.msg.html

(cl:defclass <ros_set_iap_cmdResult> (roslisp-msg-protocol:ros-message)
  ((iap_result
    :reader iap_result
    :initarg :iap_result
    :type cl:fixnum
    :initform 0)
   (error_code
    :reader error_code
    :initarg :error_code
    :type cl:fixnum
    :initform 0))
)

(cl:defclass ros_set_iap_cmdResult (<ros_set_iap_cmdResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <ros_set_iap_cmdResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'ros_set_iap_cmdResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name segway_msgs-msg:<ros_set_iap_cmdResult> is deprecated: use segway_msgs-msg:ros_set_iap_cmdResult instead.")))

(cl:ensure-generic-function 'iap_result-val :lambda-list '(m))
(cl:defmethod iap_result-val ((m <ros_set_iap_cmdResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader segway_msgs-msg:iap_result-val is deprecated.  Use segway_msgs-msg:iap_result instead.")
  (iap_result m))

(cl:ensure-generic-function 'error_code-val :lambda-list '(m))
(cl:defmethod error_code-val ((m <ros_set_iap_cmdResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader segway_msgs-msg:error_code-val is deprecated.  Use segway_msgs-msg:error_code instead.")
  (error_code m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <ros_set_iap_cmdResult>) ostream)
  "Serializes a message object of type '<ros_set_iap_cmdResult>"
  (cl:let* ((signed (cl:slot-value msg 'iap_result)) (unsigned (cl:if (cl:< signed 0) (cl:+ signed 65536) signed)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) unsigned) ostream)
    )
  (cl:let* ((signed (cl:slot-value msg 'error_code)) (unsigned (cl:if (cl:< signed 0) (cl:+ signed 65536) signed)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) unsigned) ostream)
    )
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <ros_set_iap_cmdResult>) istream)
  "Deserializes a message object of type '<ros_set_iap_cmdResult>"
    (cl:let ((unsigned 0))
      (cl:setf (cl:ldb (cl:byte 8 0) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) unsigned) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'iap_result) (cl:if (cl:< unsigned 32768) unsigned (cl:- unsigned 65536))))
    (cl:let ((unsigned 0))
      (cl:setf (cl:ldb (cl:byte 8 0) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) unsigned) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'error_code) (cl:if (cl:< unsigned 32768) unsigned (cl:- unsigned 65536))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<ros_set_iap_cmdResult>)))
  "Returns string type for a message object of type '<ros_set_iap_cmdResult>"
  "segway_msgs/ros_set_iap_cmdResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'ros_set_iap_cmdResult)))
  "Returns string type for a message object of type 'ros_set_iap_cmdResult"
  "segway_msgs/ros_set_iap_cmdResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<ros_set_iap_cmdResult>)))
  "Returns md5sum for a message object of type '<ros_set_iap_cmdResult>"
  "be52641e4ba63aab27e54ebeb837880e")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'ros_set_iap_cmdResult)))
  "Returns md5sum for a message object of type 'ros_set_iap_cmdResult"
  "be52641e4ba63aab27e54ebeb837880e")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<ros_set_iap_cmdResult>)))
  "Returns full string definition for message of type '<ros_set_iap_cmdResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%int16  iap_result  #3: iap_state_complete; 4: iap_state_fail; 5: iap_state_abort~%int16  error_code  #When iap_result value is 4, this value represents the error code~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'ros_set_iap_cmdResult)))
  "Returns full string definition for message of type 'ros_set_iap_cmdResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%int16  iap_result  #3: iap_state_complete; 4: iap_state_fail; 5: iap_state_abort~%int16  error_code  #When iap_result value is 4, this value represents the error code~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <ros_set_iap_cmdResult>))
  (cl:+ 0
     2
     2
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <ros_set_iap_cmdResult>))
  "Converts a ROS message object to a list"
  (cl:list 'ros_set_iap_cmdResult
    (cl:cons ':iap_result (iap_result msg))
    (cl:cons ':error_code (error_code msg))
))
