// Auto-generated. Do not edit!

// (in-package segway_msgs.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;

//-----------------------------------------------------------

class ros_set_iap_cmdFeedback {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.iap_percent = null;
    }
    else {
      if (initObj.hasOwnProperty('iap_percent')) {
        this.iap_percent = initObj.iap_percent
      }
      else {
        this.iap_percent = 0;
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type ros_set_iap_cmdFeedback
    // Serialize message field [iap_percent]
    bufferOffset = _serializer.int16(obj.iap_percent, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type ros_set_iap_cmdFeedback
    let len;
    let data = new ros_set_iap_cmdFeedback(null);
    // Deserialize message field [iap_percent]
    data.iap_percent = _deserializer.int16(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    return 2;
  }

  static datatype() {
    // Returns string type for a message object
    return 'segway_msgs/ros_set_iap_cmdFeedback';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return '9d75959811f859fb95f1d61fcc99a07b';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    int16  iap_percent
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new ros_set_iap_cmdFeedback(null);
    if (msg.iap_percent !== undefined) {
      resolved.iap_percent = msg.iap_percent;
    }
    else {
      resolved.iap_percent = 0
    }

    return resolved;
    }
};

module.exports = ros_set_iap_cmdFeedback;
