// Auto-generated. Do not edit!

// (in-package segway_msgs.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;

//-----------------------------------------------------------

class ros_set_iap_cmdResult {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.iap_result = null;
      this.error_code = null;
    }
    else {
      if (initObj.hasOwnProperty('iap_result')) {
        this.iap_result = initObj.iap_result
      }
      else {
        this.iap_result = 0;
      }
      if (initObj.hasOwnProperty('error_code')) {
        this.error_code = initObj.error_code
      }
      else {
        this.error_code = 0;
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type ros_set_iap_cmdResult
    // Serialize message field [iap_result]
    bufferOffset = _serializer.int16(obj.iap_result, buffer, bufferOffset);
    // Serialize message field [error_code]
    bufferOffset = _serializer.int16(obj.error_code, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type ros_set_iap_cmdResult
    let len;
    let data = new ros_set_iap_cmdResult(null);
    // Deserialize message field [iap_result]
    data.iap_result = _deserializer.int16(buffer, bufferOffset);
    // Deserialize message field [error_code]
    data.error_code = _deserializer.int16(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    return 4;
  }

  static datatype() {
    // Returns string type for a message object
    return 'segway_msgs/ros_set_iap_cmdResult';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return 'be52641e4ba63aab27e54ebeb837880e';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    int16  iap_result  #3: iap_state_complete; 4: iap_state_fail; 5: iap_state_abort
    int16  error_code  #When iap_result value is 4, this value represents the error code
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new ros_set_iap_cmdResult(null);
    if (msg.iap_result !== undefined) {
      resolved.iap_result = msg.iap_result;
    }
    else {
      resolved.iap_result = 0
    }

    if (msg.error_code !== undefined) {
      resolved.error_code = msg.error_code;
    }
    else {
      resolved.error_code = 0
    }

    return resolved;
    }
};

module.exports = ros_set_iap_cmdResult;
